//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleSystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter LoginID:.
        /// </summary>
        internal static string EnterLogin {
            get {
                return ResourceManager.GetString("EnterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password:.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose: 
        ///1:Terminal 
        ///2:Month Overview
        ///3:Exit.
        /// </summary>
        internal static string MenuChooseSystem {
            get {
                return ResourceManager.GetString("MenuChooseSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business trip:.
        /// </summary>
        internal static string MonthBS {
            get {
                return ResourceManager.GetString("MonthBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday hours spent:.
        /// </summary>
        internal static string MonthHoliday {
            get {
                return ResourceManager.GetString("MonthHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Office:.
        /// </summary>
        internal static string MonthHomeOffice {
            get {
                return ResourceManager.GetString("MonthHomeOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime hours:.
        /// </summary>
        internal static string MonthOvertime {
            get {
                return ResourceManager.GetString("MonthOvertime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick hours:.
        /// </summary>
        internal static string MonthSick {
            get {
                return ResourceManager.GetString("MonthSick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total hours worked:.
        /// </summary>
        internal static string MonthTotalHours {
            get {
                return ResourceManager.GetString("MonthTotalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Enter to Continue....
        /// </summary>
        internal static string PressKey {
            get {
                return ResourceManager.GetString("PressKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose:
        ///1:Work Entry / Continue
        ///2:LunchBreak start
        ///3:Doctor
        ///4:Bussiness Trip
        ///5:Private
        ///6:Exit
        ///0:LogOut.
        /// </summary>
        internal static string TerminalMenu {
            get {
                return ResourceManager.GetString("TerminalMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong input try again.
        /// </summary>
        internal static string WrongInputError {
            get {
                return ResourceManager.GetString("WrongInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong login / password combination.
        /// </summary>
        internal static string WrongLoginPassError {
            get {
                return ResourceManager.GetString("WrongLoginPassError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered login doesn&apos;t exist.
        /// </summary>
        internal static string WrongUser {
            get {
                return ResourceManager.GetString("WrongUser", resourceCulture);
            }
        }
    }
}
